'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppShell } from '../components/navigation';
import { EmptyState, Icon, StatusBadge } from '../components/ui';
import { authFetch } from '../lib/api';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api';
type Campaign = { id: string; name: string; status: string; firstActionAt: string | null; secondIntervalDays: number | null; secondStartTime: string | null; thirdIntervalDays: number | null; thirdStartTime: string | null; _count: { convocations: number } };
export default function CampaignsPage() {
  const [items, setItems] = useState<Campaign[]>([]); const [message, setMessage] = useState('');
  const load = async () => { const response = await authFetch(`${API}/campaigns`); if (response.ok) setItems(await response.json()); else setMessage('Não foi possível carregar as campanhas.'); };
  useEffect(() => { void load(); }, []);
  async function action(campaign: Campaign, operation: 'schedule' | 'pause' | 'resume' | 'cancel') { if (operation === 'cancel' && !window.confirm(`Cancelar a campanha “${campaign.name}”? Os disparos futuros serão bloqueados.`)) return; setMessage(''); const response = await authFetch(`${API}/campaigns/${campaign.id}/${operation}`, { method: 'POST' }); setMessage(response.ok ? 'Campanha atualizada.' : await errorOf(response)); if (response.ok) await load(); }
  return <AppShell title="Campanhas" eyebrow="Operação" actions={<Link className="button" href="/importacoes"><Icon name="plus"/>Nova campanha</Link>}><p className="content-lead">Acompanhe a programação e controle a execução sem perder o histórico.</p>{message ? <p className={message === 'Campanha atualizada.' ? 'success' : 'error'}>{message}</p> : null}<section className="panel"><header className="panel-header"><div><h2>Todas as campanhas</h2><span className="muted">{items.length} campanhas cadastradas</span></div><button className="button secondary"><Icon name="filter"/>Filtros</button></header>{items.length ? <div className="table-wrap"><table><thead><tr><th>Campanha</th><th>Pacientes</th><th>Primeira convocação</th><th>Follow-ups</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><div className="cell-main"><strong style={{ color: 'var(--navy)' }}>{item.name}</strong><small>ID {item.id.slice(0,8)}</small></div></td><td><strong>{item._count.convocations}</strong></td><td>{item.firstActionAt ? new Date(item.firstActionAt).toLocaleString('pt-BR') : '—'}</td><td><div className="cell-main"><span>2ª: +{item.secondIntervalDays ?? '—'} dias às {item.secondStartTime ?? '—'}</span><small>3ª: +{item.thirdIntervalDays ?? '—'} dias às {item.thirdStartTime ?? '—'}</small></div></td><td><StatusBadge value={item.status}/></td><td><div className="actions">{item.status === 'DRAFT' ? <button className="button small" onClick={() => void action(item,'schedule')}>Programar</button> : null}{['SCHEDULED','RUNNING'].includes(item.status) ? <button className="button secondary small" onClick={() => void action(item,'pause')}>Pausar</button> : null}{item.status === 'PAUSED' ? <button className="button small" onClick={() => void action(item,'resume')}>Retomar</button> : null}{!['CANCELLED','COMPLETED'].includes(item.status) ? <button className="button danger small" onClick={() => void action(item,'cancel')}>Cancelar</button> : null}</div></td></tr>)}</tbody></table></div> : <EmptyState title="Nenhuma campanha criada" description="Aprove uma importação para configurar a primeira campanha."/>}</section></AppShell>;
}
async function errorOf(response: Response) { const data = await response.json().catch(() => null) as { message?: string | string[] } | null; return Array.isArray(data?.message) ? data.message.join(', ') : data?.message ?? 'Não foi possível atualizar a campanha.'; }
